# Generated by Django 5.0.6 on 2025-10-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('api_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(choices=[('ip', 'IP'), ('domain', 'Domain'), ('hash', 'Hash'), ('url', 'URL')], max_length=16)),
                ('value', models.TextField(db_index=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iocs', to='ioc.source')),
            ],
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(max_length=64)),
                ('confidence', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ioc1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corr_from', to='ioc.ioc')),
                ('ioc2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corr_to', to='ioc.ioc')),
            ],
            options={
                'unique_together': {('ioc1', 'ioc2', 'match_type')},
            },
        ),
        migrations.AddIndex(
            model_name='ioc',
            index=models.Index(fields=['ioc_type', 'value'], name='ioc_ioc_ioc_typ_3acb8c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ioc',
            unique_together={('ioc_type', 'value', 'source')},
        ),
    ]
