# Generated by Django 5.0.6 on 2025-10-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ioc', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ioc',
            unique_together=set(),
        ),
    ]
