# Generated by Django 5.0.6 on 2025-11-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc', '0002_alter_ioc_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correlation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ioc',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AlterField(
            model_name='correlation',
            name='confidence',
            field=models.FloatField(default=0.5, help_text='Confidence score for this correlation (0–1).'),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='match_type',
            field=models.CharField(help_text="Rule or reason for the match, e.g. 'same_ip', 'same_domain'.", max_length=64),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='confidence',
            field=models.FloatField(default=0.5, help_text='Confidence score between 0 and 1.'),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='first_seen',
            field=models.DateTimeField(blank=True, help_text='When this IOC was first observed (if known).', null=True),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='ioc_type',
            field=models.CharField(choices=[('ip', 'IP'), ('domain', 'Domain'), ('hash', 'Hash'), ('url', 'URL')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Automatically updated when this record is saved.'),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='source',
            field=models.ForeignKey(help_text='Which feed / source reported this IOC.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iocs', to='ioc.source'),
        ),
        migrations.AlterField(
            model_name='ioc',
            name='value',
            field=models.TextField(db_index=True, help_text='The raw IOC value (IP address, domain, hash, URL, etc.).'),
        ),
        migrations.AlterField(
            model_name='source',
            name='api_url',
            field=models.URLField(blank=True, help_text='Base API URL for this source (if applicable).'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(blank=True, help_text="Optional: e.g. 'ip-reputation', 'malware-feed', etc.", max_length=64),
        ),
    ]
