import React, { useEffect, useMemo, useState } from 'react'
import Header from './components/Header.jsx'
import Filters from './components/Filters.jsx'
import IOCTable from './components/IOCTable.jsx'
import CorrelationsTable from './components/CorrelationsTable.jsx'
import StatCard from './components/StatCard.jsx'
import { listIocs, listCorrelations, listSources, correlateNow } from './services/api.js'

export default function App() {
  const [iocs, setIocs] = useState([])
  const [corr, setCorr] = useState([])
  const [sources, setSources] = useState([])

  const [type, setType] = useState('')
  const [sourceFilter, setSource] = useState('')
  const [search, setSearch] = useState('')

  const loadAll = async () => {
    console.log('[UI] Reload All clicked')
    try {
      const [i, c, s] = await Promise.all([listIocs(), listCorrelations(), listSources()])
      setIocs(i); setCorr(c); setSources(s)
      console.log('[UI] Reloaded ->', { iocs: i.length, corr: c.length, sources: s.length })
      alert(`Reloaded ✓  IOCs: ${i.length}  Corr: ${c.length}  Sources: ${s.length}`)
    } catch (e) {
      console.error('[UI] Reload failed', e)
      alert('Reload failed. See console.')
    }
  }

  const runCorrelation = async () => {
    console.log('[UI] Run Correlation Now clicked')
    try {
      const res = await correlateNow()
      console.log('[API] correlateNow ->', res)
      const c = await listCorrelations()
      setCorr(c)
      alert(`Correlation created: ${res?.created ?? 0}`)
    } catch (e) {
      console.error('[UI] Correlate failed', e)
      alert('Correlation failed. See console.')
    }
  }

  useEffect(() => { loadAll() }, [])

  const filteredIocs = useMemo(() =>
    iocs.filter(row => {
      if (type && row.ioc_type !== type) return false
      if (sourceFilter && !(row.source?.name || '').toLowerCase().includes(sourceFilter.toLowerCase())) return false
      if (search && !(row.value || '').toLowerCase().includes(search.toLowerCase())) return false
      return true
    }),
  [iocs, type, sourceFilter, search])

  const stats = useMemo(() => ({
    iocs: iocs.length, correlations: corr.length, sources: sources.length
  }), [iocs, corr, sources])

  return (
    <div className="container">
      <Header />

      <div className="grid grid-3" style={{marginTop:16}}>
        <StatCard label="Total IOCs" value={stats.iocs} hint="Fetched from all feeds / sources" />
        <StatCard label="Correlations" value={stats.correlations} hint="Generated by server" />
        <StatCard label="Sources" value={stats.sources} hint="OTX / AbuseIPDB / MalwareBazaar / etc." />
      </div>

      <div className="row" style={{marginTop:16}}>
        <button type="button" className="btn" onClick={loadAll}>Reload All</button>
        <button type="button" className="btn" onClick={runCorrelation}>Run Correlation Now</button>
      </div>

      <div style={{marginTop:16}}>
        <Filters
          type={type} setType={setType}
          source={sourceFilter} setSource={setSource}
          search={search} setSearch={setSearch}
          onRefresh={loadAll}
        />
      </div>

      <div className="grid" style={{marginTop:16}}>
        <IOCTable data={filteredIocs.slice(0, 200)} />
        <CorrelationsTable data={corr.slice(0, 200)} />
      </div>
    </div>
  )
}
